### ISSUE TITLE
Support for Clojars dependencies

### ISSUE THREAD

**Issue by samuela** [Geal/sbt-clojure#1]
It would be really nice if the plugin automatically handled clojars dependencies à la leiningen. How are clojure dependencies handled currently?

**Comment by samuela** [comment]
For future reference, here's a set up that worked well for me. In `build.sbt`:

``` scala
...
resolvers += "clojars" at "http://clojars.org/repo/"
libraryDependencies += "instaparse" % "instaparse" % "1.4.0"
...
```

**Comment by Geal** [comment]
Great tip, thanks!
